import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { Providers } from "@/src/client/Providers/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Taskora",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  // theme format: "light" | "dark" | "system" | "teal-light" | "teal-dark" | "cyan-light" | "cyan-dark"
  const theme = (session?.user as any)?.theme ?? "system";

  return (
    <html lang="pt-br" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = ${JSON.stringify(theme)};

                  // theme format examples:
                  //   "light"       → class="light"
                  //   "dark"        → class="dark"
                  //   "system"      → class="light" or "dark" based on prefers-color-scheme
                  //   "teal-light"  → class="theme-teal"
                  //   "teal-dark"   → class="dark theme-teal"
                  //   "cyan-light"  → class="theme-cyan"
                  //   "cyan-dark"   → class="dark theme-cyan"

                  var root = document.documentElement;
                  root.classList.remove('light', 'dark', 'theme-teal', 'theme-cyan');

                  var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

                  if (theme === 'system') {
                    root.classList.add(prefersDark ? 'dark' : 'light');
                  } else if (theme === 'light') {
                    root.classList.add('light');
                  } else if (theme === 'dark') {
                    root.classList.add('dark');
                  } else if (theme === 'teal-light') {
                    root.classList.add('theme-teal');
                  } else if (theme === 'teal-dark') {
                    root.classList.add('dark', 'theme-teal');
                  } else if (theme === 'cyan-light') {
                    root.classList.add('theme-cyan');
                  } else if (theme === 'cyan-dark') {
                    root.classList.add('dark', 'theme-cyan');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <Toaster richColors position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
